# This is a basic workflow to help you get started with Actions

name: gadi compile

on:
  push:
    branches: [ gadi_install ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_gadi:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    
    # Runs a single command using the runners shell
    - name: Get an env variable
      run: |
        echo ${GITHUB_REF##*/}
        echo ${{ github.ref }}

    # Runs a set of commands using the runners shell
    - name: ls on gadi
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ls -a
        host: "gadi.nci.org.au"
        username: ${{ secrets.GADI_UNAME }}
        password: ${{ secrets.GADI_PWORD }}
        #passphrase: ${{ secrets.GADI_PASSPHRASE }}
        #privateKey: ${{ secrets.GADI_PRIVATE_KEY }}
